# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_clientprofile_hostprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('color', models.CharField(choices=[('white', 'white'), ('grey', 'grey'), ('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('yellow', 'yellow')], default='white', max_length=20, verbose_name='color')),
            ],
            options={
                'verbose_name': 'catagory',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='meeting/%Y/%m', verbose_name='image')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('start', models.DateTimeField(db_index=True, verbose_name='start of the meeting')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end of the meeting')),
                ('private', models.BooleanField(default=True, help_text='unmark if you want this meeting to be seen by clients', verbose_name='private')),
                ('public', models.BooleanField(default=False, help_text='mark if you want this meeting to be public(for everyone)', verbose_name='public')),
                ('slug', models.SlugField(verbose_name='url name')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='calendars.Category', verbose_name='category')),
                ('clients', models.ManyToManyField(blank=True, db_index=True, to='users.ClientProfile')),
                ('hosts', models.ManyToManyField(db_index=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='tags',
            field=models.ManyToManyField(blank=True, to='calendars.Tag', verbose_name='tags'),
        ),
    ]
