# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_auto_20160626_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='meeting',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='calendars.Meeting', verbose_name='meeting'),
            preserve_default=False,
        ),
    ]
