# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20160626_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='calendars.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meeting/%Y/%m', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='calendars.Tag', verbose_name='tags'),
        ),
    ]
