# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_auto_20160626_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together=set([]),
        ),
    ]
