# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0007_auto_20160627_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='hosts',
            field=models.ManyToManyField(db_index=True, to='users.HostProfile'),
        ),
    ]
